### ISSUE TITLE
test code

### ISSUE THREAD

**Issue by zengchan** [ZhuangPeiyu/ReLoc#2]
When testing, do you only call the loc model for images? Do you need to compress the images first？

**Comment by ZhuangPeiyu** [comment]
The answer to the first and the second question is no. The testing images should be fed into the restoration module first.

**Comment by zengchan** [comment]
What I understand is that during the test, the image is directly input to the restore model without the compress operation, and then the output is used as the input of the loc model, right? Can test scripts be open source？

**Comment by ZhuangPeiyu** [comment]
Your understanding is right. This paper is under review now. The trained model and code will be released after this paper is accepted.

**Comment by zengchan** [comment]
Good luck and good luck with your paper！

**Comment by ZhuangPeiyu** [comment]
Thanks!

**Comment by zengchan** [comment]
I used your code to train the Casia dataset. I wrote my own test script, but the effect is not very good. Any suggestions for parameter adjustment or triaining？

**Comment by ZhuangPeiyu** [comment]
Some suggestions are as follows.
1. Pre-train the localization module with I_Plain first and observe if the localization module achieves satisfactory performance on the I_plain dataset. If not, it is recommended to replace it with a more powerful localization module. Because the performance on I_Plain is the upper bound of the ReLoc on I_D.
2. Balance the training image resolution. Too large will increase the training difficulty of the restoration module, and too small will increase the training difficulty of the localization network. In our experiments, cropping the image into 128*128 is working.

**Comment by ZhuangPeiyu** [comment]
The newest codes and checkpoints are released.
